name: Build

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"
  pull_request:
    branches: ["main"]
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write
  actions: write
  contents: read
  packages: write

jobs:
  build-and-push-container:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build environment
        id: setup_build_env
        uses: ./.github/actions/setup-image-build-env
        with:
          quay-username: ${{ secrets.QUAY_IO_USERNAME }}
          quay-password: ${{ secrets.QUAY_IO_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            quay.io/pixelgen-technologies/proxiome-analysis-template
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      # Build and push base image
      - name: Build base Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          target: build
          platforms: linux/amd64
          load: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
